# Generated by Django 4.2.2 on 2023-08-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
