# Generated by Django 4.2.2 on 2023-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_texta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=20)),
            ],
        ),
    ]
